### ISSUE TITLE
WebUI Document that hidden files (.file) is counted !

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs-webui#92]
![image](https://user-images.githubusercontent.com/3321281/193014018-7a534fe9-f8c9-4879-8548-41c40b9c8eb7.png)

@tbsbdr

**Comment by tbsbdr** [comment]
![](https://user-images.githubusercontent.com/26610733/193014216-b19c0a1e-9a98-46fa-8d06-dbc203e52238.png)

![](https://user-images.githubusercontent.com/26610733/193014356-9ee0fa2b-e29f-4a5d-84e0-2cbb15462da2.png)

**Comment by mmattel** [comment]
Closing via #109
